version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ../:/app
        networks:
            - internal

    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ../:/app
        depends_on:
            - php
        networks:
            - internal
    
    mysql:
        image: mariadb:latest
        env_file:
            - ../database.env # Configure mysql
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - internal

networks:
    internal:
        driver: bridge

volumes:
    mysqldata: